name: SurvivalBoomChat
version: '${version}'
main: net.survivalboom.survivalboomchat.SurvivalBoomChat
api-version: '1.20'
softdepend: ["SkinsRestorer"]

website: "https://survivalboom.net"
authors: [TIMURishche, SurvivalBoom Network 2024]
folia-supported: true


commands:
  survivalboomchat:
    description: "Головна команда SurvivalBoomChat"
    aliases:
      - sbchat
  ignore:
    description: "Ігнорувати гравця"

libraries:
  - org.json:json:20231013