name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the source code
    - name: Checkout sources
      uses: actions/checkout@v4

    # Set up Java JDK 17
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    # Set up Gradle
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    # Cache Gradle dependencies
    - name: Cache Gradle Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Make gradlew executable
    - name: Setup Permissions
      run: chmod +x gradlew

    # Build the project using Gradle
    - name: Build with Gradle
      run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Check out the source code
    - name: Checkout sources
      uses: actions/checkout@v4

    # Set up Java JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generate and submit a dependency graph for Dependabot Alerts
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3.1.0
